service: my-mercedes-alexa-skill

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'} # default stage is dev, but you can override it.
  region: us-east-1 # Alexa is only available in eu-west-1 or us-east-1
  memorySize: 256
  cfLogs: true # AWS Cloudformation logging

functions:
  skill:
    handler: index.handler # path to the alexa handler - {path}/{filename}.{handler function}
    description: My Mercedes Alexa skill
    events:
      - alexaSkill
      
plugins:
  - serverless-webpack
custom:
  webpackIncludeModules: true